[package]
name = "automata"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30"
vello = "0.3"
rayon = "1.10"
clap = { version = "4.5", features = ["derive"] }
wgpu = "22"
pollster = "0.3"
